dist: bionic
language: node_js
node_js:
  - 11
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run prettier
deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  cleanup: false
  edge: true # opt in to dpl v2
  local_dir: dist
  verbose: true
  fqdn: kotin.ga
